import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { LoginBtn, LogOutBtn } from "./LoginBtn";
import { getServerSession } from "next-auth";
import { authOptions } from "@/pages/api/auth/[...nextauth]";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const loginSession = await getServerSession(authOptions);
  if (loginSession) {
    // console.log(logingSession);
  }
  return (
    <html lang="en">
      <body>
        <div className="navbar">
          <Link href="/" className="logo">
            Appleforum
          </Link>
          <Link href="/list">List</Link>
          {loginSession ? (  
            <span>
              {loginSession.user.name} <LogOutBtn />{" "}
            </span>
          ) : (
            <LoginBtn></LoginBtn>
          )}
        </div>
         {/* Context를 사용하지 않고 각 페이지에 props를 통해 로그인 정보를 전달하는 방법, 권장되지않지만 사용해보자 */}
         {/* {React.Children.map(children, child => {
          if (React.isValidElement(child)) {
            return React.cloneElement(child, { loginSession });
          }
          return child;
        })} */}
        {children}
      </body>
    </html>
  );
}
